from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name="books.index"),
    path('list_books/', views.list_books, name="books.list_books"),
    path('<int:bookId>/', views.viewbook, name="books.view_one_book"),
    path('aboutus/', views.aboutus, name="books.aboutus"),
    path('html5/links/', views.links, name="books.links"),
    path('html5/text/formatting/', views.formatting, name="books.formatting"),
    path('html5/listing/', views.listing, name="books.listing"),
    path('html5/tables/', views.tables, name="books.tables"),
    path('search/', views.search_view, name="books.search"),
    path('books/simple/query/', views.simple_query, name="books.simple_query"),
    path('books/complex/query/', views.complex_query, name="books.complex_query"),
    path('books/lab8/task1', views.lab8_task1, name='lab8_task1'),
    path('books/lab8/task2', views.lab8_task2, name='lab8_task2'),
    path('books/lab8/task3', views.lab8_task3, name='lab8_task3'),
    path('books/lab8/task4', views.lab8_task4, name='lab8_task4'),
    path('books/lab8/task5', views.lab8_task5, name='lab8_task5'),
    path('books/lab8/task7', views.lab8_task7, name='lab8_task7'),
    path('books/lab9/task1', views.lab9_task1, name='lab9_task1'),
    path('books/lab9/task2', views.lab9_task2, name='lab9_task2'),
    path('books/lab9/task3', views.lab9_task3, name='lab9_task3'),
    path('books/lab9/task4', views.lab9_task4, name='lab9_task4'),
    path('books/lab9/task5', views.lab9_task5, name='lab9_task5'),
    path('books/lab9/task6', views.lab9_task6, name='lab9_task6'),
    path('books/lab9_part1/listbooks', views.lab9_part1_listbooks),
    path('books/lab9_part1/addbook', views.lab9_part1_addbook),
    path('books/lab9_part1/editbook/<int:id>', views.lab9_part1_editbook),
    path('books/lab9_part1/deletebook/<int:id>', views.lab9_part1_deletebook),
    path('books/lab9_part2/listbooks',views.lab9_part2_listbooks),
    path('books/lab9_part2/addbook',views.lab9_part2_addbook),
    path('books/lab9_part2/editbook/<int:id>',views.lab9_part2_editbook),
    path('books/lab9_part2/deletebook/<int:id>',views.lab9_part2_deletebook),
]